# Generated by Django 3.1 on 2021-02-08 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_remove_cmmsuser_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name of Area(eg. Utility, Area 100, CO2)', max_length=50, null=True)),
                ('description', models.CharField(help_text='Enter description of Area', max_length=200, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department')),
            ],
            options={
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name of Risk(eg. safety, enviromental)', max_length=50, null=True)),
                ('description', models.CharField(help_text='Enter description of Risk', max_length=200, null=True)),
                ('value', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name of Unit(eg. Boiler, Membrane, Cooling Tower)', max_length=50, null=True)),
                ('description', models.CharField(help_text='Enter description of Unit', max_length=200, null=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.area')),
            ],
            options={
                'ordering': ['area', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name of Equipment(eg. TI-4102, C-018, P-021)', max_length=50, null=True)),
                ('description', models.CharField(help_text='Enter description of Equipment', max_length=200, null=True)),
                ('rbmValue', models.IntegerField(null=True)),
                ('rbmGrade', models.CharField(help_text='Enter grade of Risk(eg. Critical, Normal, Less)', max_length=50, null=True)),
                ('risks', models.ManyToManyField(help_text='Select risks', to='equipment.Risk')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.unit')),
            ],
            options={
                'ordering': ['unit', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name of Category(eg. Motor, Compressor...)', max_length=50, null=True)),
                ('description', models.CharField(help_text='Enter description of Category', max_length=200, null=True)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.section')),
            ],
            options={
                'ordering': ['section', 'name'],
            },
        ),
    ]
