# Generated by Django 3.1 on 2021-02-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name of Activity(eg. Cleaning, Greasing, Covering)', max_length=50, null=True)),
                ('description', models.CharField(help_text='Enter description of Activity', max_length=200, null=True)),
                ('duration', models.IntegerField(null=True)),
                ('manPower', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PM_PdM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name of Activity(eg. PM Motor AC)', max_length=50, null=True)),
                ('description', models.CharField(help_text='Enter description of PM_PdM', max_length=200, null=True)),
                ('mode', models.CharField(help_text='Enter mode of PM_PdM (eg. Running, Stop)', max_length=200, null=True)),
                ('activities', models.ManyToManyField(help_text='Select activities', to='pm_pdm.Activity')),
            ],
            options={
                'ordering': ['mode', 'name'],
            },
        ),
    ]
