# Generated by Django 3.1 on 2020-10-03 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20201003_1111'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wo_priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name of section(eg. Normal, Emergency)', max_length=20, null=True)),
                ('description', models.CharField(help_text='Enter description of priority', max_length=100, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Work_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_number', models.CharField(max_length=20, null=True)),
                ('tagnumber', models.CharField(help_text='Enter tagnumber(eg. FT-1405)', max_length=50, null=True)),
                ('problem', models.TextField(max_length=1000, null=True)),
                ('date_open', models.DateField()),
                ('date_finish', models.DateField(null=True)),
                ('current_user_id', models.IntegerField(null=True)),
                ('executor_user_id', models.IntegerField(null=True)),
                ('dest_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.section')),
                ('originator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('priority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='work_order.wo_priority')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.action')),
            ],
            options={
                'ordering': ['originator', 'status', 'wo_number'],
            },
        ),
        migrations.CreateModel(
            name='Wo_journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, null=True)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.action')),
                ('concern_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='work_order.work_order')),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='Wo_instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField(max_length=1000, null=True)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='work_order.work_order')),
            ],
        ),
        migrations.CreateModel(
            name='Wo_completion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.TextField(help_text='Enter activity', max_length=1000, null=True)),
                ('manPower', models.TextField(help_text='Man power name', max_length=100, null=True)),
                ('material', models.TextField(help_text='Enter material', max_length=500, null=True)),
                ('tool', models.TextField(help_text='Enter action', max_length=500, null=True)),
                ('date', models.DateField(null=True)),
                ('duration', models.IntegerField(help_text='Enter duration (hours)', null=True)),
                ('acted_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.action')),
                ('work_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='work_order.work_order')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
